require 'psych'
require 'sass'
require 'haml'
require 'i18n'
require 'i18n/backend/fallbacks'
require 'rack/contrib/locale'
require 'rack/contrib/nested_params'
require 'rack/contrib/post_body_content_type_parser'
require 'sprockets-helpers'
require 'sinatra'
require 'sinatra/param'
require 'sinatra/json'
require 'sinatra/streaming'
require 'json'
require 'uglifier'
require 'rack/protection'

require 'active_support/core_ext/kernel/reporting'
require 'active_support/core_ext/object/blank'
require 'active_support/core_ext/array/access'
require 'active_support/core_ext/hash/keys'
require 'active_support/core_ext/string/inflections'

require 'timeout'
require 'logger'
require 'pager'
require 'psych'
require 'addressable/uri'
require 'securerandom'

require 'test_server/exceptions'
require 'test_server/config'
require 'test_server/ui_logger'
require 'test_server/error_handler'
require 'test_server/access_logger'
require 'test_server/error_messages'
require 'test_server/main'
require 'test_server/template_repository'
require 'test_server/null_access_logger'

module TestServer; end
