post_install() {
  echo ""
  echo "Please place a config file at one of the following places:"
  echo ""
  echo " * $HOME/.config/test_server/config.yaml"
  echo " * $HOME/.test_server/config.yaml"
  echo " * /etc/test_server/config.yaml"
  echo ""
  echo "The package contains a \"config.yaml\" which has been placed at /etc/test_server/config.yaml during package install. Feel free to modify it."
  echo ""
}

post_upgrade() {
  post_install
}
